[build]
  command = "npm run build"
  functions = "api/"
  publish = "build"

[dev]
  command = "npm start"
  publish = "public"
  functions = "api/"
  Port = 8888
  functionsPort = 8080
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200